[feed/activity] fixed Infinity seconds ago Bug #46
openwisp/OpenWISP-Website pull request #48
Opened 2020-10-01 15:08 UTC by WinstonPais

Fixed the issue which caused the activity feed to show "Infinity seconds ago". Caused by dividing by 0.
Used a ternary expression to check if the denominator is 0 if it is just display the seconds elapsed.

Fixes #46 

![Screenshot_4](https://user-images.githubusercontent.com/51374812/94827345-f3789880-0425-11eb-8245-8b58f0f70efd.png)

2020-10-01 16:41 UTC, nemesisdesign requested changes
@WinstonPais you have to add `Fixes #46` at the end:

``` 
...

Fixes #46 
``` 

Thanks!

2020-10-01 23:14 UTC, nemesisdesign reviewed
@WinstonPais How did you replicate the bug?
I would like to double check that your patch really fixes the issue, can you help me in doing so?

2020-10-02 06:29 UTC, WinstonPais commented
> @WinstonPais How did you replicate the bug?
> I would like to double check that your patch really fixes the issue, can you help me in doing so?

@nemesisdesign I just kept starring and un-starring the repository. Then compared the actual website and the local one to see the difference.

2020-10-02 13:19 UTC, dwang commented
The fix works for me locally 👍 

After you amend the commit to change the message, you need to force push for the changes to show up on GitHub.

2020-10-02 16:49 UTC, nemesisdesign approved these changes
Thanks @dwang for testing it.

2020-10-02 16:50 UTC, merged