[add] Added an Error 404 page #55 issue:
openwisp/OpenWISP-Website pull request #65
Opened 2023-03-07 15:50 UTC by AdarshRawat1

Added Error 404 page.

2023-03-07 21:54 UTC, nemesisdesign requested changes
Please follow the commit message guidelines, eg:

```
[change] Add 404 page #55 

Closes #55
```

2023-03-07 21:54 UTC, nemesisdesign commented on 404.html
> +                    <h3 class="error-msg">THE PAGE YOU ARE LOOKING FOR DOESN'T EXIST.<br>
do not use all uppercase please

2023-03-07 21:54 UTC, nemesisdesign commented on 404.html
> +</html>
ensure the file ends with a blank line

2023-03-07 21:54 UTC, nemesisdesign commented on index.html
> +    }</script>
Google Cloud will take care of showing the 404 page when needed. Please remove this.

2023-03-08 07:31 UTC, Aryamanz29 commented on css/404.css
> +}
Please add a blank line here.

2023-03-08 07:32 UTC, Aryamanz29 commented on css/404.css
> +}
Please add a blank line here.

2023-03-08 07:39 UTC, Aryamanz29 commented
Hey @AdarshRawat1! 
Your PR title and commit message still don't follow our commit guidelines.
Also make sure QA checks passes when running `./run-qa-checks` script locally.
Please read : https://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly

2023-03-08 15:23 UTC, AdarshRawat1 commented
Sir @Aryamanz29 @nemesisdesign  , I'll make a new pull request with all the necessary corrections. Thank you for your feedback.

2023-03-08 15:23 UTC, closed without merging