Closes #55
openwisp/OpenWISP-Website pull request #66
Opened 2023-03-08 15:33 UTC by AdarshRawat1

[Add] Added error 404 page

2023-03-13 11:48 UTC, Aryamanz29 commented on css/404.css
> +    transform: translateY(0) rotate(0deg);
Please add this `CSS` unit to  https://github.com/openwisp/OpenWISP-Website/blob/master/.stylelintrc.json#L17

2023-03-13 11:49 UTC, Aryamanz29 commented on css/404.css
> +    transform: translateY(-800px) rotate(360deg);
Same here

2023-03-13 11:58 UTC, Aryamanz29 requested changes
Please change your commit PR title and commit message:

Run this command:

```bash
git commit --amend
```
Change your commit message to:
```
[change] Added error 404 page #55
Closes #55
```
and then always double check by running `./run-qa-checks` script on your development environment.

2023-03-13 12:00 UTC, Aryamanz29 requested changes
PR title : [change] Added error 404 page #55

2023-03-13 12:03 UTC, Aryamanz29 commented on 404.html
> +    </div>
You can remove this tag (`/div`) since tags must be paired, i.e., no start tag `<div>`.

2023-03-13 17:27 UTC, Aryamanz29 requested changes
Looks good @AdarshRawat1! but there is one minor change you must make to pass the quality assurance check.
I found that in your commit message, you've only changed the commit title, not the commit message body, i.e, `Closes #issue_number` is still missing.

To change that you've to run the following command on terminal:

```bash
git commit --amend
```

and change your commit message to:
```
# This should be your commit title
[change] Added error 404 page #55

# This should be your commit message body
Closes #55
```

and then you can force push to re-write this commit
```
git push origin master -f
```

2023-03-13 17:36 UTC, Aryamanz29 commented
Hey @AdarshRawat1 If you're facing any issues with setting up this project and running QA checks script, you can[ follow README instructions](https://github.com/Aryamanz29/OpenWISP-Website/tree/add-readme) that I have recently added in https://github.com/openwisp/OpenWISP-Website/pull/67.

2023-03-13 18:38 UTC, Aryamanz29 submitted a review, later dismissed
Thanks @AdarshRawat1! I have tested your changes locally, and QA checks also passed. It looks good to me!

Deferring merge to @nemesisdesign.

![Screenshot from 2023-03-14 00-04-28](https://user-images.githubusercontent.com/56113566/224797519-86c70bcd-1dd2-4859-a348-b896a282e4d4.png)

![Screenshot from 2023-03-13 23-58-58](https://user-images.githubusercontent.com/56113566/224797233-7bdd7f79-b2d2-49d3-a8f9-7f1e6234f68c.png)

2023-03-13 21:53 UTC, nemesisdesign requested changes
> Thanks @AdarshRawat1! I have tested your changes locally, and QA checks also passed. It looks good to me!
> 
> Deferring merge to @nemesisdesign.
> 
> ![Screenshot from 2023-03-14 00-04-28](https://user-images.githubusercontent.com/56113566/224797519-86c70bcd-1dd2-4859-a348-b896a282e4d4.png)
> 
> ![Screenshot from 2023-03-13 23-58-58](https://user-images.githubusercontent.com/56113566/224797233-7bdd7f79-b2d2-49d3-a8f9-7f1e6234f68c.png)

Why is the background different from the rest of the site?
The look and feel must be consistent. We cannot design different colors every time we add a new page, that is not the best practice.

2023-03-14 03:12 UTC, AdarshRawat1 commented
> > Thanks @AdarshRawat1! I have tested your changes locally, and QA checks also passed. It looks good to me!
> > Deferring merge to @nemesisdesign.
> > ![Screenshot from 2023-03-14 00-04-28](https://user-images.githubusercontent.com/56113566/224797519-86c70bcd-1dd2-4859-a348-b896a282e4d4.png)
> > ![Screenshot from 2023-03-13 23-58-58](https://user-images.githubusercontent.com/56113566/224797233-7bdd7f79-b2d2-49d3-a8f9-7f1e6234f68c.png)
> 
> Why is the background different from the rest of the site? The look and feel must be consistent. We cannot design different colors every time we add a new page, that is not the best practice.

Should I remove the animation feature or simply change the color scheme?

2023-03-14 15:07 UTC, nemesisdesign reviewed
> > > Thanks @AdarshRawat1! I have tested your changes locally, and QA checks also passed. It looks good to me!
> > > Deferring merge to @nemesisdesign.
> > > ![Screenshot from 2023-03-14 00-04-28](https://user-images.githubusercontent.com/56113566/224797519-86c70bcd-1dd2-4859-a348-b896a282e4d4.png)
> > > ![Screenshot from 2023-03-13 23-58-58](https://user-images.githubusercontent.com/56113566/224797233-7bdd7f79-b2d2-49d3-a8f9-7f1e6234f68c.png)
> > 
> > 
> > Why is the background different from the rest of the site? The look and feel must be consistent. We cannot design different colors every time we add a new page, that is not the best practice.
> 
> Should I remove the animation feature or simply change the color scheme?

We need a VERY SIMPLE 404 page with a consistent look and feel as the rest of the website. Adopt the KISS principle.

2023-03-15 03:31 UTC, AdarshRawat1 commented
> > > > Thanks @AdarshRawat1! I have tested your changes locally, and QA checks also passed. It looks good to me!
> > > > Deferring merge to @nemesisdesign.
> > > > ![Screenshot from 2023-03-14 00-04-28](https://user-images.githubusercontent.com/56113566/224797519-86c70bcd-1dd2-4859-a348-b896a282e4d4.png)
> > > > ![Screenshot from 2023-03-13 23-58-58](https://user-images.githubusercontent.com/56113566/224797233-7bdd7f79-b2d2-49d3-a8f9-7f1e6234f68c.png)
> > > 
> > > 
> > > Why is the background different from the rest of the site? The look and feel must be consistent. We cannot design different colors every time we add a new page, that is not the best practice.
> > 
> > 
> > Should I remove the animation feature or simply change the color scheme?
> 
> We need a VERY SIMPLE 404 page with a consistent look and feel as the rest of the website. Adopt the KISS principle.

I acknowledge your instructions and have carried out the required actions. Kindly review the changes and inform me if any further adjustments are necessary.

2023-03-18 15:31 UTC, nemesisdesign requested changes
It's looking better but you need to strictly adhere to the same HTML structure used in other pages, which is not being done here and hence the margin between elements looks odd and you had to add extra dividers and `<br>` elements which is not the way to go. This page is not consistent with the rest of the website.

2023-03-18 15:31 UTC, nemesisdesign commented on 404.html
> +    </script>
this script section can be removed

2023-03-18 15:31 UTC, nemesisdesign commented on 404.html
> +    <title>Error 404</title>
```suggestion
    <title>Page Not Found (404)</title>
```

2023-03-18 15:31 UTC, nemesisdesign commented on 404.html
> +            <h2>The page you are looking for doesn't exist.<br>
```suggestion
            <h2>The page you're looking for can't be found.</h2>
```

2023-03-18 15:31 UTC, nemesisdesign commented on 404.html
> +        <div align="center">
you're not following the structure of the other pages, please see how other content pages have "<article>" and the classes they usea and follow the same structure.

2023-03-18 15:31 UTC, nemesisdesign commented on 404.html
> +            <div class="ui hidden divider"></div>
get rid of these

2023-03-18 15:31 UTC, nemesisdesign commented on 404.html
> +            <h1>Error 404!<br></h1>
```suggestion
            <h1>Page Not Found (404)</h1>
```

2023-03-18 15:31 UTC, nemesisdesign commented on 404.html
> +                <br>
remove the extra BRs

2023-03-18 15:31 UTC, nemesisdesign commented on 404.html
> +            <p class="buttons center">
fix the indentation here

2023-03-18 16:15 UTC, AdarshRawat1 commented
Kindly review the changes and guide me if any further adjustments are necessary.

2023-03-24 20:47 UTC, nemesisdesign approved these changes
Thanks!

2023-03-24 20:49 UTC, merged