[activityFeed] Sanitize HTML content in activity feed #54
openwisp/OpenWISP-Website pull request #75
Opened 2023-10-21 17:33 UTC by kunal232i

Any content that includes HTML or JS from GitHub is now properly sanitized to prevent third parties from triggering any potentially harmful code when viewing the activity feed. Example: The text "<input>" is rendered as "&lt;input&gt;" and not as an actual HTML input.

Fixes #54

2023-10-23 07:56 UTC, nemesifier requested changes

2023-10-23 07:56 UTC, nemesifier commented on js/feed.js
> +            .replace(/<br>(?!.*<br>)/g, "#####TEMPBR#####")
why is this necessary?

2023-10-23 08:35 UTC, kunal232i commented on js/feed.js
> +            .replace(/<br>(?!.*<br>)/g, "#####TEMPBR#####")
To skip the last &lt;br&gt; tag that is added in the case of "push event".
https://github.com/openwisp/OpenWISP-Website/blob/653e1fb00c7fcee730347a157ca9819d5ed0d35d/js/feed.js#L149-L157

2023-10-23 08:59 UTC, kunal232i commented on js/feed.js
> +            .replace(/<br>(?!.*<br>)/g, "#####TEMPBR#####")
Oh, wait I didn't see the map. let me fix it in a few time.

2023-10-23 09:33 UTC, kunal232i commented
Hello @nemesifier, I have implemented the requested changes. Please review them at your convenience.

2023-10-25 09:27 UTC, kunal232i commented
Hello @nemesifier, this is a gentle reminder to review this code. The code has passed through ./run-qa-checks, and it could prevent any future vulnerabilities to the site. Here are some screenshots.

![image](https://github.com/openwisp/OpenWISP-Website/assets/81668653/398cca08-de57-4697-95e5-4f1736d22605)

![image](https://github.com/openwisp/OpenWISP-Website/assets/81668653/9828b5d1-e52f-4a87-a7a5-6c23a313aff8)

2023-10-27 17:37 UTC, nemesifier approved these changes

2023-10-27 17:38 UTC, merged

2023-10-27 17:38 UTC, nemesifier commented
Thanks @kunal232i :clap: :+1: